### PR TITLE
update sha.js to 2.3.2

### PR DESCRIPTION
**Pull request by dominictarr**
this uses the changes from https://github.com/dominictarr/sha.js/pull/17
(mostly cleaning up code, and with a small perf increase on small inputs)

### CODE REVIEW

**Comment by dcousens** [comment]
ACK, but maybe wait for https://github.com/dominictarr/sha.js/pull/18 ?

**Comment by dominictarr** [comment]
yup

**Comment by dominictarr** [comment]
done.

**Comment by calvinmetcalf** [comment]
3.9.3

**Pull request merged**
