### PR TITLE
bn.js to 1.0.0 in all deps

### PR DESCRIPTION
**Pull request by calvinmetcalf**
with much thanks to @guybedford and @indutny

### CODE REVIEW

**Comment by guybedford** [comment]
:+1:

**Comment by calvinmetcalf** [comment]
@dominictarr @dcousens either of you able to take a quick look?

**Comment by dcousens** [comment]
Will check today

**Comment by calvinmetcalf** [comment]
@dcousens thanks!

**Comment by guybedford** [comment]
Perfect - that's ironed out all the forks!

**Pull request merged**
